version: '3'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orm
      PGDATA: /pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data